### ISSUE TITLE
monitor.py

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#92]
I have updated and want to try monitor.py, seems like my system is missing some file?

```
/gpuowl/tools# ./monitor.py 
GPU UID            VDD   SCLK MCLK Mem-used Mem-busy PWR  FAN  Temp     PCIeErr
Traceback (most recent call last):
  File "./monitor.py", line 75, in <module>
    printInfo(devices, readSlow)
  File "./monitor.py", line 64, in printInfo
    gpu = readGpu(d, readSlow)
  File "./monitor.py", line 44, in readGpu
    uid = read(device + 'unique_id')
  File "./monitor.py", line 21, in read
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/drm/card0/device/unique_id'

```

and I take the occasion to say Merry Christmas.

**Comment by preda** [comment]
Thank you!
it seems unique_id only exists on recent Linux kernel (5.5, 5.4) or when using rocm-dkms from a recent ROCm. I added a more elegant fallback when the file is not found.

**Comment by valeriob01** [comment]
Great! I think it is not the only file missing, will try to upgrade asap:

```
gpuowl/tools# ./monitor.py -h
GPU UID            VDD   SCLK MCLK Mem-used Mem-busy PWR  FAN  Temp     PCIeErr
Traceback (most recent call last):
  File "./monitor.py", line 81, in <module>
    printInfo(devices, readSlow)
  File "./monitor.py", line 70, in printInfo
    gpu = readGpu(d, readSlow)
  File "./monitor.py", line 57, in readGpu
    hwmon = hwmonPath(device)
  File "./monitor.py", line 18, in hwmonPath
    return hwmonBase + os.listdir(hwmonBase)[0] + '/'
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/drm/card0/device/hwmon/'

```
